version: 0.2
env:
  git-credential-helper: yes
phases:

  install:
    on-failure: ABORT
    commands:
       - "git config --global user.email 'dev@appland.se'"
       - "git config --global user.name 'AWS CodeBuild'"
       - "git checkout $CODEBUILD_SOURCE_VERSION"
       - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > ~/.npmrc
       - npm install -g npm@8.5.2 node-pre-gyp
       - npm install --legacy-peer-deps
       - npm --version
       - node --version
       - git status
       - echo "$CODEBUILD_SOURCE_VERSION"
  build:
    on-failure: ABORT
    commands:
       - npm run build
       - |-
            if [ "$IS_PREBUILD" = 'true' ]; then
              echo "Publishing release candidate"
              npm version pre$NPM_VERSION --preid=rc
              cd build
              npm publish --access-public --tag=next
            else
              echo "Publishing release"
              npm version $NPM_VERSION
              cd build
              npm publish --access-public --tag=latest
            fi
            cd ..
       - export TAG=$(cat package.json | jq -r '.version')
       - git push --set-upstream origin $CODEBUILD_SOURCE_VERSION
       - git push origin --tags
  post_build:
    on-failure: ABORT
    commands:
       - cd $CODEBUILD_SRC_DIR_rob0ui
       - export PACKAGE="https://registry.npmjs.org/@applandstream/streaming-view-sdk/-/streaming-view-sdk-$TAG.tgz";
       - "git checkout $CODEBUILD_SOURCE_VERSION_rob0ui"
       - "jq --arg \"NEXT_VERSION\" \"$TAG\" '.dependencies.\"@applandstream/streaming-view-sdk\" = $NEXT_VERSION' package.json > package.json.tmp"
       - mv package.json.tmp package.json
       - "jq --arg \"NEXT_VERSION\" \"$TAG\" '.packages.\"\".dependencies.\"@applandstream/streaming-view-sdk\" = $NEXT_VERSION' package-lock.json | jq --arg \"NEXT_VERSION\" \"$PACKAGE\" '.packages.\"node_modules/streaming-view-sdk\".resolved = $NEXT_VERSION' | jq --arg \"NEXT_VERSION\" \"$PACKAGE\" '.dependencies.\"@applandstream/streaming-view-sdk\".version = $TAG' | jq --arg \"NEXT_VERSION\" \"PACKAGE\" '.dependencies.\"@applandstream/streaming-view-sdk\".resolved = $NEXT_VERSION' > package-lock.json.tmp"
       - mv package-lock.json.tmp package-lock.json
       - "git commit -am \"Build System: Update of the Appland SDK version v$TAG\""
       - "test \"$UPDATE_SDK_ON_ROB0_APPLAND_UI\" = 'true' && git push --set-upstream origin $CODEBUILD_SOURCE_VERSION_rob0ui || echo 'skip update of the Rob0 Appland UI'"
       - "echo \"Build successful, create GIT tag: $TAG\""
